# Generated by Django 2.1.3 on 2018-11-29 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='author',
            new_name='registration_open',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_start_date',
            field=models.DateField(),
        ),
    ]
