# Generated by Django 2.1.3 on 2018-11-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20181129_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='registration_status',
            new_name='open_for_registration',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_category',
            field=models.CharField(choices=[('CNF', 'Conference'), ('SMR', 'Seminar'), ('PRS', 'Presentation'), ('RGS', 'Religious'), ('SPR', 'Spiritual'), ('SCL', 'Social'), ('GNR', 'Not Specified')], default='GNR', max_length=100),
        ),
    ]
