# Generated by Django 2.1.3 on 2018-11-30 16:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20181130_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_end_time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='event_start_time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='event_start_date',
            field=models.DateField(),
        ),
    ]
