# Generated by Django 2.1.3 on 2018-11-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20181130_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_start_time',
            field=models.TimeField(),
        ),
    ]
