# Generated by Django 2.1.3 on 2018-12-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_auto_20181130_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=models.ImageField(blank=True, upload_to='event_pics'),
        ),
    ]
