# Generated by Django 2.1.3 on 2018-12-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_event_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_registration',
            name='contact_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='event_registration',
            name='quantity_adult',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='event_registration',
            name='quantity_child',
            field=models.IntegerField(null=True),
        ),
    ]
